### ISSUE TITLE
Server crash after summoning mobs using command block

### ISSUE THREAD

**Issue by srnyx** [The-Fireplace-Minecraft-Mods/Erroring-Entity-Remover#1]
**Describe the bug**
I clicked a button on a command block to spawn a few mobs and it crashed the server.

**To Reproduce**
1. Get a command block
2. Input /summon mob
3. Set it to repeating and needs redstone
4. Attach a button and click on it

**Logs/Screenshots/Videos**
https://pastebin.com/f2KLVvCB

**Versions (please complete the following information, do *NOT* say "latest"):**
 - Minecraft: 1.16.5
 - Mod Version: latest
 - Fabric API: latest

**Comment by srnyx** [comment]
Alright, I'm very dumb, I didn't even have the mod installed...
Sorry

**Comment by The-Fireplace** [comment]
FYI, please fill in the requested information next time. This could have been avoided if you had checked for it. Thanks!
![Screenshot_20210218-132123.jpg](https://user-images.githubusercontent.com/5914284/108409825-48a62280-71ec-11eb-8a42-29a333d8eb69.jpg)

**Comment by srnyx** [comment]
> FYI, please fill in the requested information next time. This could have been avoided if you had checked for it. Thanks!
> ![Screenshot_20210218-132123.jpg](https://user-images.githubusercontent.com/5914284/108409825-48a62280-71ec-11eb-8a42-29a333d8eb69.jpg)

Apparently, I'm also blind... sorry lmfao
